name: insplash
description: Unsplash client written on Flutter.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.1.1
  logger: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  flutter_bloc: ^8.1.2
  # Local cache
  cached_network_image: ^3.2.3
  # DI
  get_it:
  get: ^4.6.5

  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
